---
- name: Borrar version anterior
  file: path=/usr/local/bin/actualizador state=absent

- name: Descargar ultima version
  git: repo=https://github.com/Grupo106/actualizador.git
       dest={{ src_path }}/actualizador
       version=master

- name: Instalar dependencias
  pip: requirements=requirements.txt chdir={{ src_path }}/actualizador

- name: Instalar
  command: python setup.py install chdir={{ src_path }}/actualizador

- name: Configurar cron
  cron: name=actualizador user=netcop special_time=hourly
        job={{ bin_path }}/actualizar
