- hosts: debian
  tasks:
#  - name: Dehabilitar login root
#    template:
#      src: templates/etc/ttys
#      dest: /etc/ttys
#    become: yes
#  - name: Habilitar claves ssh
#    template:
#      src: templates/ssh/authorized_keys
#      dest: /home/morfeo/.ssh/authorized_keys
#    become: yes
#  - name: Generar password aleatoria para usuario {{ ansible_user_id }}
#    raw: cat /dev/urandom | tr -dc a-zA-Z0-9 | head -c 50 |
#         pw mod user {{ ansible_user_id }} -h 0
#    become: yes
  - name: Habilitar interfaz bridge
    template:
      src: templates/etc/network/interfaces
      dest: /etc/network/interfaces
    become: yes
  - name: Instalar screen
    apt: name=screen
    become: yes
