- hosts: all
  become: yes
  vars:
    - postgresql_version: 9.4 # version de postgres a utilizar
    - postgresql_db: morfeo
    - postgresql_user: morfeo
    - postgresql_password: morfeo
    - src_path: /usr/local/src # directorio donde se guardara el codigo fuente

  # Tasks
  # =========================================================================
  
  # utilidades
  # -------------------------------------------------------------------------
  tasks:
  - name: Instalar dependencias
    apt: name={{ item }}
    with_items:
      - bridge-utils
      - git
      - make
      - gcc
      - locales

  - name: Instalar paquetes opcionales
    apt: name={{ item }}
    with_items:
      - screen
      - vim
  

  # postgresql
  # -------------------------------------------------------------------------
  - name: Crear locales
    locale_gen: name=en_US.UTF-8 state=present

  - name: Instalar PostgreSQL {{ postgresql_version }}
    apt: name={{ item }}
    notify: crear cluster
    with_items:
      - python-psycopg2
      - postgresql-{{ postgresql_version }}

  - name: Habilitar servicio postgresql
    service: name=postgresql enabled=yes state=started

  - name: Configurar permisos
    template: src=templates/pg_hba.conf
              dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf

 # - copy: src=templates/schema.sql dest=/tmp/schema.sql

 # - name: Crear schema
 #   command: psql -f /tmp/schema.sql
 #   become_user: "{{ postgresql_user }}"

 # - file: name=/tmp/schema.sql state=absent

  - name: Crear base de datos
    postgresql_db: name=morfeo
    become_user: postgres
  
  - name: Crear usuario Postgresql
    postgresql_user: name={{ postgresql_user }}
                     password={{ postgresql_password }}
                     db={{ postgresql_db }} 
    become_user: postgres


  # adquisidor
  # -------------------------------------------------------------------------
  - name: Instalar dependencias adquisidor
    apt: name={{ item }}
    with_items:
      - libecpg-dev
      - libpcap0.8-dev
  
  - name: Descargar ultima version del adquisidor
    git: repo=https://github.com/Grupo106/adquisidor.git
         dest={{ src_path }}/adquisidor
         version=master

  - name: Compilar e instalar adquisidor
    command: make {{ item }} chdir={{ src_path }}/adquisidor
    with_items:
      - clean
      - release
      - install
    environment:
      POSTGRESQL_DB: "{{ postgresql_db }}"
      POSTGRESQL_USER: "{{ postgresql_user }}"
      POSTGRESQL_PASSWORD: "{{ postgresql_password }}"


  # configuracion de red
  # -------------------------------------------------------------------------
  - name: Configurar interfaces de red
    template:
      src: templates/etc/network/interfaces
      dest: /etc/network/interfaces
    notify:
      - reboot

  # Handlers
  # =========================================================================
  handlers:
  - name: crear cluster
    command: pg_createcluster {{ postgresql_version }} main --start

  - name: reboot
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true
