- hosts: all
  become: yes
  vars:
    - postgresql_version: 9.4

  # Tasks
  # -----------------------------------------------------------------------
  tasks:
  #- name: Instalar screen
  #  apt: name=screen
  - name: Instalar bridge-utils
    apt: name=bridge-utils
    notify: crear interfaz br0

  - name: Configurar interfaces de red
    template:
      src: templates/etc/network/interfaces
      dest: /etc/network/interfaces
    notify:
      - reboot

#  - name: Instalar PostgreSQL {{ postgresql_version }}
#    apt: name=postgresql-{{ postgresql_version }}
#    notify: crear cluster
#
#  - name: Habilitar servicio postgresql
#    service: name=postgresql enabled=yes state=started

  # Handlers
  # -----------------------------------------------------------------------
  handlers:
  - name: crear cluster
    command: pg_createcluster {{ postgresql_version }} main --start

  - name: reboot
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true
