---
- name: Instalar dependencias
  apt: name={{ item }}
  with_items:
    - bridge-utils
    - git
    - make
    - gcc
    - locales
    - ntp

- name: Desinstalar pip
  apt: name=python-pip state=absent

- name: Instalar pip
  easy_install: name=pip

- name: Configurar sudo
  template: src=templates/sudoers.d.j2
            dest=/etc/sudoers.d/netcop
            mode=0440

- name: Configurar grub
  lineinfile: dest=/etc/default/grub regexp=^GRUB_TIMEOUT= line=GRUB_TIMEOUT=0
  notify: reconfigurar grub

- name: Instalar paquetes opcionales
  apt: name={{ item }}
  with_items:
    - screen
    - vim
    - dnsutils
  when: not production

- name: Configurar banner
  template: src=templates/motd.j2
            dest=/etc/motd

- name: Configurar red
  template: src=templates/interfaces.j2
            dest=/etc/network/interfaces
  notify:
    - reiniciar red

- name: Configurar puente de red
  template: src=templates/br0.j2
            dest=/etc/network/interfaces.d/br0
  notify:
    - reiniciar red

- name: Deshabilitar IPv6
  lineinfile:
      dest: /etc/sysctl.conf
      line: net.ipv6.conf.all.disable_ipv6=1
  notify:
    - reiniciar red
