---
- name: Descargar ultima version
  git: repo=https://github.com/Grupo106/configurador.git
       dest={{ src_path }}/configurador
       version=master

- name: Instalar dependencias
  pip: requirements=requirements.txt chdir={{ src_path }}/configurador

- name: Instalar
  command: python setup.py install chdir={{ src_path }}/configurador

- name: Configurar cron
  cron: name=configurador user=root minute="*/1"
        job="{{ bin_path }}/configurador --set"
